exclude: docs/.*
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-executables-have-shebangs
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: no-commit-to-branch
        args: [--branch, main]
-   repo: local
    hooks:
    -   id: generate-documentation
        name: Generate Haddock documentation
        entry: scripts/generate_docs.sh
        language: script
        always_run: true
        pass_filenames: false
    -   id: run-tests
        name: Run code tests
        entry: scripts/run_tests.sh
        language: script
        always_run: true
        pass_filenames: false
    -   id: lint
        name: Lint with stylish-haskell
        entry: scripts/lint.sh
        language: script
        always_run: true
        pass_filenames: false
    -   id: headroom
        name: Check module headers
        entry: scripts/headroom.sh
        language: script
        always_run: true
        pass_filenames: false
