steps:
  - records:
      equals: "indent 2"
      first_field: "same_line"
      field_comment: 2
      deriving: 2
      via: "indent 2"
      sort_deriving: false
  - simple_align:
      cases: always
      top_level_patterns: always
      records: always
  - imports:
      align: file
      list_align: after_alias
      pad_module_names: true
      long_list_align: multiline
      empty_list_align: inherit
      list_padding: module_name
      separate_lists: true
      space_surround: false
      group_imports: true
  - language_pragmas:
      style: vertical
      remove_redundant: true
  - trailing_whitespace: {}
columns: 80
newline: native
cabal: true
