steps:
  - simple_align:
      cases: false
      top_level_patterns: false
      records: false
  - imports:
      align: none
      list_align: after_alias
      pad_module_names: false
      long_list_align: new_line
      empty_list_align: inherit
      list_padding: 2
      separate_lists: false
      space_surround: false
# NOTE: if you don't want language pragmas to be affected, remove these lines.
# Otherwise, uncomment and set style to `compact`, `vertical` or `compact_line`
# as you prefer.
  - language_pragmas:
      style: vertical
      remove_redundant: true
  - trailing_whitespace: {}
columns: 100
newline: native
language_extensions:
  - OverloadedStrings
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - FlexibleContexts
  - RankNTypes
  - GADTs
  - RecordWildCards
  - TemplateHaskell
