# Ensure that if any source files change, that CHANGELOG.ms has also change
name: Check CHANGELOG.md on PR

on:
    pull_request:
        branches:
            - main
        paths:
            - '**.hs'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - uses: danieljimeneznz/ensure-files-changed@v4.1.0
              with:
                  require-changes-to: CHANGELOG.md
                  token: ${{ secrets.GITHUB_TOKEN }}
